"""cascade on delete for stories, passages

Revision ID: 6bd343cfc662
Revises: f7696c81ff37
Create Date: 2026-04-07 13:20:06.819503

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bd343cfc662"
down_revision: Union[str, Sequence[str], None] = "f7696c81ff37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.drop_constraint("stories_creator_id_fkey", "stories", type_="foreignkey")
    op.create_foreign_key(
        op.f("stories_creator_id_fkey"),
        "stories",
        "users",
        ["creator_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "passages_parent_passage_id_fkey", "passages", type_="foreignkey"
    )
    op.drop_constraint("passages_story_id_fkey", "passages", type_="foreignkey")
    op.drop_constraint("passages_author_id_fkey", "passages", type_="foreignkey")
    op.create_foreign_key(
        op.f("passages_parent_passage_id_fkey"),
        "passages",
        "passages",
        ["parent_passage_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("passages_story_id_fkey"),
        "passages",
        "stories",
        ["story_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("passages_author_id_fkey"),
        "passages",
        "users",
        ["author_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("passages_author_id_fkey"), "passages", type_="foreignkey")
    op.drop_constraint(op.f("passages_story_id_fkey"), "passages", type_="foreignkey")
    op.drop_constraint(
        op.f("passages_parent_passage_id_fkey"), "passages", type_="foreignkey"
    )
    op.create_foreign_key(None, "passages", "passages", ["parent_passage_id"], ["id"])
    op.create_foreign_key(None, "passages", "users", ["author_id"], ["id"])
    op.create_foreign_key(None, "passages", "stories", ["story_id"], ["id"])
    op.drop_constraint(op.f("stories_creator_id_fkey"), "stories", type_="foreignkey")
    op.create_foreign_key(None, "stories", "users", ["creator_id"], ["id"])
    # ### end Alembic commands ###
